const PERMISSION = {
  PROJECT_READ: "PROJECT_READ",
  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_UPDATE: "PROJECT_UPDATE",
  PROJECT_DELETE: "PROJECT_DELETE",

  TASK_READ: "TASK_READ",
  TASK_CREATE: "TASK_CREATE",
  TASK_UPDATE: "TASK_UPDATE",
  TASK_DELETE: "TASK_DELETE",
  TASK_UPDATE_STATUS: "TASK_UPDATE_STATUS",
  TASK_ASSIGN: "TASK_ASSIGN",
  TASK_DEPENDENCY_CREATE: "TASK_DEPENDENCY_CREATE",
  TASK_ATTACHMENT_CREATE: "TASK_ATTACHMENT_CREATE",
  TASK_COMMENT_CREATE: "TASK_COMMENT_CREATE",
};

export default PERMISSION;
